
generator:
  datasource:
    # mysql or oracle, default mysql
    type: oracle
    url: jdbc:oracle:thin:@192.168.1.120:1521:orcl
    username: user_jjfj1
    password: user_jjfj1

  package: com.zjyc.fgt
  ignore-col: del,add,BH
  pk-name: BH
  prefix: T_
  template:
    path: jjfj_old
    mapping: |
      Entity.java.vm: main/java/{packagePath}/database/model/{className}.java
      Dao.java.vm: main/java/{packagePath}/database/dao/{className}Dao.java
#      Model.java.vm: main/java/{packagePath}/database/model/{className}.java
#      Dao.java.vm: main/java/{packagePath}/database/model/{className}Dao.java
#      Mapper.vm: main/java/{packagePath}/database/model/{className}Mapper.xml
#      Example.java.vm: main/java/{packagePath}/database/model/{className}Example.java

